#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Leevi Graham - http://nicolasgallagher.com/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/leevigraham/dotfiles/

Copyright (c) Leevi Graham
Licensed under the MIT license.
EOT

}
